### ISSUE TITLE
Should every exception thrown from the Link be of type LinkException?

### ISSUE THREAD

**Issue by TarekkMA** [gql-dart/gql#100]
I'm building my own link that utilizes ``dio`` for making HTTP requests instead of ``http`` library. dio have multiple types of errors should I remap them to a exceptions that extend LinkException?

for example, should I do the following or rethrow expectations other than the ones in the ``gql_link`` library?

```dart
} on dio.DioError catch (e) {
  if (e.type != dio.DioErrorType.RESPONSE) {
    final res = e.response;
    if (res.data is Map<String, dynamic>) {
      final parsedResponse =
          parser.parseResponse(res.data as Map<String, dynamic>);
      throw DioLinkServerException(
          response: res, parsedResponse: parsedResponse);
    }
  }else if (e.type == dio.DioErrorType.CONNECT_TIMEOUT){
    throw DioLinkTimeoutException(originalException:e);
  }
  else if(...){
    ...
    throw DioLinkXXXException(originalException:e);
  }
}catch (e){
  throw DioLinkUnkownException(originalException:e);
}
```

And as I can see the ``ferry`` client only catches LinkException.
https://github.com/gql-dart/ferry/blob/master/lib/src/client/client.dart#L171

**Comment by klavs** [comment]
Yes, that is the intention to always return `LinkException`.
https://github.com/gql-dart/gql/blob/master/gql_link/lib/src/exceptions.dart

I guess you can re-wrap the dio exception within one of the `LinkException` subclasses.
My intention with `LinkException` is to mark the action where the exception occured.

I recently implemented more verbose error handling in `gql_http_link`
https://github.com/gql-dart/gql/blob/master/gql_http_link/lib/src/link.dart

That said, it has not yet been proven to be a good idea in practice. Feedback is appreciated.

**Comment by TarekkMA** [comment]
okay, for now, I will wrap the exceptions to follow the convention. Thanks a lot for your great hard work.
