### ISSUE TITLE
What packages can be used to build graphql server?

### ISSUE THREAD

**Issue by wurikiji** [gql-dart/gql#109]
I am interested in building graphql server (not using angel framework and its packages). 
In this project, what packages can be used to build graphql server? 
If you give me a rough idea, it will really be appreciated.

**Comment by klavs** [comment]
I am not aware of any other server-side GraphQL packages for Dart.

At some point in future I'll want to be able to write client-side GraphQL resolvers, and I assume the same logic could be used on the server-side as well.

Unfortunately, that's not coming soon.

**Comment by agent3bood** [comment]
If you want dart package there is https://github.com/angel-dart/angel
Otherwise you can use any server-side language (for example Apollo Server. or Hasura).

**Comment by agent3bood** [comment]
Closing, not an issue.
