### ISSUE TITLE
 [gql_build] [BUG] Can not have types with 'value' as property

### ISSUE THREAD

**Issue by Gustav0ar** [gql-dart/gql#118]
When the Graphql type has a property with name _value_ it will generate schema.gql.dart file with duplicated property names. This happens mostly when using Hasura and its feature [Enum](https://hasura.io/docs/1.0/graphql/manual/schema/enums.html) which you have a Type with _value_ and _comment_ properties. Here is an example of such issue:

```
class role_select_column {
  const role_select_column(this.value);

  final String value;

  static const role_select_column comment = role_select_column('comment');

  static const role_select_column value = role_select_column('value');

  @override
  int get hashCode => value.hashCode;
  @override
  bool operator ==(Object o) => o is role_select_column && o.value == value;
}
```

I'm not sure what would be the correct approach to fix this issue, my best guess is to rename `String value` property to something else when it detects that there is a property with same name.

**Comment by smkhalsa** [comment]
@Gustav0ar we've made some significant changes to the generators since this issue was filed. Are you still experiencing this issue in the latest version?

**Comment by Gustav0ar** [comment]
> @Gustav0ar we've made some significant changes to the generators since this issue was filed. Are you still experiencing this issue in the latest version?

Sorry but I'm not using this package anymore. We went another way, because there was no way to work around this issue. There was also problem that this package requires some outdated packages that was causing conflicts in my pubspec

**Comment by smkhalsa** [comment]
@Gustav0ar Thanks for letting me know. I'm closing this for now.
