### ISSUE TITLE
[gql_http_link] Add response headers to context

### ISSUE THREAD

**Issue by micimize** [gql-dart/gql#119]
In `graphql-flutter` I closed an issue about a specific solution for accessing response headers a while ago, but never followed up with the correct solution (adding headers to context)

https://github.com/zino-app/graphql-flutter/issues/371

**Comment by joshuadeguzman** [comment]
Hey @micimize,

I am using cookies for authenticating my requests. I found a [workaround](https://github.com/zino-app/graphql-flutter/issues/592)) at least for now for achieving it.

Curious about your thoughts in terms of performance passing a custom http client.

Thank you!

**Comment by micimize** [comment]
@joshuadeguzman any performance hit would be due to the overall performance diff between `dio` and `http`, which I would expect to be at most negligible. Also `http` also has some serious long-standing open issues that do not inspire confidence
