### ISSUE TITLE
[gql_build] multiple queries in one file?

### ISSUE THREAD

**Issue by knaeckeKami** [gql-dart/gql#120]
Hi,

I was trying out gql_build and ran into an issue:

I defined a schema.graphql file and added a queries.graphql file, where I added multiple queries (say, Query1, Query2, Query3) with different required variables.

This does not seem to work.
In the queries.ast.gql.dart file, there is a line

```dart
      const document = _i1.DocumentNode(definitions: [Query1, Query2, Query3 ...]);
```

If I then execute

```dart
    graphqlClient
        .responseStream(Query1(
            buildVars: (vars) => vars..query1Var = "test"
      )
```

All Queries (Query1, Query2, Query3) will be executed, but of course, this query fails as the variables for the latter 2 queries are not set.
If I split all the queries in separate files, they work fine.

Is having multiple queries in one .graphql file supported?
If yes, this should be fixed.
If not, this should probably be an error during the build_runner step.

**Comment by klavs** [comment]
Hey @knaeckeKami, In GraphQL it is valid to have multiple operations in a single file, but you must provide the name of the operation you want to execute. It should be a server error otherwise.

**Comment by knaeckeKami** [comment]
So, suppose I have the following test.graphql file:



```graphql
query Test1{
    articles{
        items{
            name
        }
    }
}

query Test2{
    products{
        items{
            name
        }
    }
}
```

In the test.op.gql.dart looks like this:

```dart
const Test1 = _i1.Operation(document: _i2.document, operationName: 'Test1');
const Test2 = _i1.Operation(document: _i2.document, operationName: 'Test2');
```

both Test1 and Test2 use the same "document", which looks like this:

```dart
const document = _i1.DocumentNode(definitions: [Test1, Test2]);
```
If I then execute the query Test1 like this:

```dart
  graphQLClient.responseStream(Test1());
```

Both the queries Test1 and Test2 will be executed, since both have the same document in the generated code.

Is this really expected behaviour?

**Comment by klavs** [comment]
```
const Test1 = _i1.Operation(document: _i2.document, operationName: 'Test1');
```
This is not optimal, but is still valid. Feel free to make a PR where only the relevant part is included (consider fragments to implement it correctly).

> Both the queries Test1 and Test2 will be executed, since both have the same document in the generated code.

This is not correct. Either your client or your server is ignoring the `operationName`. Best way to continue the investigation would be to check your network traffic for the presence of that `operationName`.

**Comment by knaeckeKami** [comment]
You're right, it seems that the server I use ignores the operation name and executes the whole query.
