### ISSUE TITLE
Cancel a subscription when the stream isn't listened to anymore...

### ISSUE THREAD

**Issue by iscriptology** [gql-dart/gql#133]
Is there anyway to cancel a subscription?
I thought it might be a nice implementation to send the server a [GQL_STOP](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_stop) payload when the stream is stopped being listened to.

What do you think?

**Comment by knaeckeKami** [comment]
I implemented this in my gql_phoenix_link package. It uses a slightly different protocol than apollo, but the concept is the same.
See https://github.com/knaeckeKami/gql_phoenix_link/blob/master/lib/src/phoenix_link.dart#L80

This works only on the master branch of ferry, as it depends on https://github.com/gql-dart/ferry/pull/53

**Comment by agent3bood** [comment]
@klavs This can be closed.
