### ISSUE TITLE
[RFC] - Use generic types for data & variables in Request & Response

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/gql#142]
Currently, the `Request.variables` and `Response.data`objects must be json (i.e. `Map<String, dynamic>`).

Therefore, in order to implement typed requests and responses (such as those used in `ferry`), we must re-implement the Request and Response classes.

I suggest we consider the following changes:

1. use generic types for data and variables in `Request`, `Response`
2. make `Request` and `Response` abstract
3. implement a default concrete implementation of `Request` and `Response` that uses json for data and vars.

For example, `Request` might look like this:

```dart
abstract class Request<TVars> {
  final Operation operation;

  final TVars variables;

  const Request({
    this.operation,
    this.variables,
  });
}
```

We could then implement a `DefaultRequest` that uses json:

```dart
class DefaultRequest extends Request<Map<String, dynamic>> {
  @override
  final Operation operation;

  @override
  final Map<String, dynamic> variables;

  final Context context;

  const DefaultRequest({
    @required this.operation,
    this.variables = const <String, dynamic>{},
    this.context = const Context(),
  })  : assert(operation != null),
        assert(context != null);

  DefaultRequest withContextEntry<T extends ContextEntry>(T entry) =>
      DefaultRequest(
        operation: operation,
        variables: variables,
        context: context.withEntry<T>(entry),
      );

  DefaultRequest updateContextEntry<T extends ContextEntry>(
    ContextUpdater<T> update,
  ) =>
      DefaultRequest(
        operation: operation,
        variables: variables,
        context: context.updateEntry<T>(update),
      );

  List<Object> _getChildren() => [
        operation,
        variables,
        context,
      ];

  @override
  bool operator ==(Object o) =>
      identical(this, o) ||
      (o is DefaultRequest &&
          const ListEquality<Object>(
            DeepCollectionEquality(),
          ).equals(
            o._getChildren(),
            _getChildren(),
          ));

  @override
  int get hashCode => const ListEquality<Object>(
        DeepCollectionEquality(),
      ).hash(
        _getChildren(),
      );
}
```

Of course, we'd also need to make changes to `gql_link` and any other libraries that depend on `gql_exec`.

**Comment by klavs** [comment]
I think it would be limiting the abilities of Link if the requests and responses were made generic.

As an example consider Apollo-style client resolvers or RESTLink. You would want to be able to split an Operation in multiple, and with that you might need to split `Request.variables` as well (to guarantee that the every new operation has exactly the required variables.

I think it's ok to leave Link how it is, but instead build a layer atop of it to make working with types easier.

**Comment by smkhalsa** [comment]
@klavs yea, that's a good point.

I've been re-working the Ferry architecture, and I realized that virtually all of the Ferry functionality could be implemented as  Links, including caching, optimism, refetching, pagination, etc. 

So rather than re-implementing an extended version of `Request`, `Response`, and `Link`, I was trying to figure out if we could just extend the existing implementations.

**Comment by smkhalsa** [comment]
I've implemented a generic type version of `Request`, `Response`, and `Link` in the `ferry_exec` package in gql-dart/ferry#96, so I'll go ahead and close this.
