### ISSUE TITLE
[discussion] Change HttpLink interface to make client custom type

### ISSUE THREAD

**Issue by agent3bood** [gql-dart/gql#154]
This discussion might be late to open, I have seen an open PR for Dio-link https://github.com/gql-dart/gql/pull/150
I want to make a suggestion and see if it is possible to implement.

instead of creating a new link for different http packages, we can change the interface of `HttpLink` and change the `_httpClient`  type.

The suggested `HttpLink` will look like
```Dart
  HttpLink(
    String uri, {
    this.defaultHeaders = const {},
    this.useGETForQueries = false,
    GqlDartHttpClient httpClient,
    this.serializer = const RequestSerializer(),
    this.parser = const ResponseParser(),
  }) : uri = Uri.parse(uri) {
    _httpClient = httpClient ?? http.Client();
  }
```

```Dart
abstract class GqlDartHttpClient {
  Response send(Request request);
}
```

This way it will be easy to implement any link, remove duplicate code which might introduce inconsistency.

Best
Abdullah

**Comment by klavs** [comment]
Let's finalize the dio merge in the coming days and then work on abstractions to make both links inter-changeable.

**Comment by agent3bood** [comment]
Thanks @klavs I will keep this open until the Dio PR is merged.

**Comment by TarekkMA** [comment]
Yes this is the best approach I was thinking of making this because I was just keeping up with the gql_http_link features

**Comment by klavs** [comment]
#150 is now merged in.
@agent3bood, @TarekkMA you have a green light. My design goal would be to either make them interchangeable or merge them in a single link using something like what @agent3bood suggested.

**Comment by agent3bood** [comment]
Hi @TarekkMA your suggestion is perfect. Do you have time to finish it?

Check this example 
```Dart
class DioClient extends GqlDartHttpClient  {
  DioClient(Dio this.dio);
  final Dio dio;

  @override
  Response send(Request request) {
    // TODO
  }
}
```

**Comment by agent3bood** [comment]
Closing reason https://github.com/gql-dart/gql/pull/157#issuecomment-817144191
