### ISSUE TITLE
[gql_code_builder] DartStyle name formatting

### ISSUE THREAD

**Issue by mit-73** [gql-dart/gql#170]
I believe that the code generator should do the formatting of the names of fields and classes in DartStyle.

The following code will help you convert the following names:

- `test_name`  > `testName`
- `_test_name ` > `_testName`
- `test_name_name_ ` >  `testNameName`
- `test_ ` >  `test`
- etc.

```
String _formatNameToDartStyle(String raw) =>
    raw.replaceAllMapped(RegExp(r"(?!^)([\_]+.?)"), (Match m) {
      final _m = m.group(0).split("");
      return _m.length > 1 ? _m.last.toUpperCase() : "";
    });
```

**Comment by smkhalsa** [comment]
This seems like it could lead to collisions. For example, what if an operation includes both `name` and `_name` fields?

**Comment by mit-73** [comment]
Yes you are right. There are two options:

1. Fix `RegExp(r"(?!^)([\_]+.?)(?!$)")`
2. Leave as is

What do you think about this?

**Comment by smkhalsa** [comment]
Closing this since it doesn't seem feasible due to potential collisions
