### ISSUE TITLE
[gql_build] NNBD

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/gql#171]
Now that `built_value` [supports NNBD](https://pub.dev/packages/built_value/versions/8.0.0-nullsafety.0/changelog), we should migrate.

**Comment by ram231** [comment]
May I know if it's a pre-release or another version with -null.safety tag?

**Comment by klavs** [comment]
I'm migrating `package:gql`

**Comment by smkhalsa** [comment]
@klavs any update on the migration?

**Comment by klavs** [comment]
Got busy with unexpected life events.
After commenting I realized that for part of the codegen it's not necessary to have `package:gql` to be migrated, although it would be nice. Also, it wouldn't be a breaking change, since it could be just a feature switch to generate NNBD ready code.
