### ISSUE TITLE
[gql_http_link] allow custom _parseHttpResponse function

### ISSUE THREAD

**Issue by agent3bood** [gql-dart/gql#176]
### Background

It is recommended to parse json in background 
https://flutter.dev/docs/cookbook/networking/background-parsing

### Issue

Right now the `gql_http_link` has a function `_parseHttpResponse` which does parse the json on the same thread as the UI thread.

### Solution

Allow passing a custom `_parseHttpResponse` 

I am working on this and will submit a PR soon.

**Comment by BaudouinCS** [comment]
Hello @agent3bood 

I have great troubles try/catching these `HttpLinkParserException` thrown from `_parseHttpResponse`.

Would you mind pointing out how to catch them for me please? Would be greatly appreciated!

Regards.

**Comment by TiffApps** [comment]
Having the same issue, would be nice to have an example

**Comment by knaeckeKami** [comment]
can you give more details?

**Comment by BaudouinCS** [comment]
@knaeckeKami See [this issue](https://github.com/heftapp/graphql_codegen/issues/214) for more details, they redirected me to this package.

If it doesn't belong to the current issue, I can open a new one for clarity.

**Comment by BaudouinCS** [comment]
@knaeckeKami Hello, have you got the opportunity to look into this by any chance?

**Comment by knaeckeKami** [comment]
the link thows an exception on status >= 300. The client that you use will probably wrap the exception in the response object.
