### ISSUE TITLE
[gql_websocket_link] catch network error 

### ISSUE THREAD

**Issue by TomVista** [gql-dart/gql#178]
at gql_websocket_link/lib/src/link.dart line 167
```
  /// Connects to the server.
  Future<void> _connect() async {
    _connectionStateController.value = connecting;  // this line
    try {
```

if network was off line unexpected,will got an error
```
StateError (Bad state: Cannot add new events after calling close)
```

**Comment by agent3bood** [comment]
Thanks for pointing this out.

I am working on this PR https://github.com/gql-dart/gql/pull/168 which will fix this error, lets wait till it is completed.
