### ISSUE TITLE
Packages that help with code generation

### ISSUE THREAD

**Issue by venkatd** [gql-dart/gql#195]
Before the GraphQL ecosystem was mature, we had built our own hacky library to generate types from a schema. But looks like the ecosystem has really grown up!

We still have very custom needs for generating GraphQL types from a schema but would like to lean on open source libraries for the hard stuff like parsing the AST and so on.

If we'd like to generate our own custom code from a GraphQL schema and a set of queries, what packages would w be be able to lean on to do the hard work?

I'm seeing gql_code_gen and gql. Are there any other packages to be aware of?

Are there any really bare bones hello-world style examples for code gen? For example, even just generating empty classes for each type and query name would be a great starting point.

Thanks!

**Comment by klavs** [comment]
[Here](https://github.com/gql-dart/gql/tree/master/codegen) we have our codegen tools, [here](https://github.com/gql-dart/gql/tree/master/examples) are examples, some of which use the before mentioned codegen tools.

These tools are opinionated and might not suite your case well. But you can take inspiration from them. The `gql` is definitelly a building block you should not reimplement yourself.

**Comment by venkatd** [comment]
Thank you! Will look into these
