### ISSUE TITLE
Package links broken in README

### ISSUE THREAD

**Issue by shyndman** [gql-dart/gql#200]
Hi there,

A number of the package links in the README are broken. Their intended destinations are easy enough to find, but I thought I should mention.

For example
* `package:gql_code_builder`
* `package:gql_code_build`
* `package:gql_exec`
* ...and so on. The entire set need a check.

**Comment by agent3bood** [comment]
Thank for pointing this out, sometimes a nudge is needed to do simple fixes.

**Comment by shyndman** [comment]
:) For sure
