### ISSUE TITLE
Dio 4.0.0 is out

### ISSUE THREAD

**Issue by teknolojia** [gql-dart/gql#206]
can we change dio_link to that version

> Because every version of gql_dio_link depends on dio ^3.0.9 and graph depends on dio ^4.0.0, gql_dio_link is forbidden.
> So, because graph depends on gql_dio_link ^0.0.4, version solving failed.
> pub get failed (1; So, because graph depends on gql_dio_link ^0.0.4, version solving failed.)
>

**Comment by agent3bood** [comment]
Hi


`dio 4` support is available in the `nullsafety` branch, which is coming soon. 

Until the null-safety version of all gql packages is release you will have to wait. 


Related PR https://github.com/gql-dart/gql/pull/194
