### ISSUE TITLE
[gql_websocket_link] Unsupported operation: Platform._version exception in flutter web

### ISSUE THREAD

**Issue by dopecoder** [gql-dart/gql#207]
Using gql_websocket_link along with ferry throws the following exception :

`Unsupported operation: Platform._version`

The exception returned by ferry looks like this : 

`ServerException(originalException: Unsupported operation: Platform._version, parsedResponse: null)`

Does this have to do with `gql_websocket_link` support for web?

**Comment by agent3bood** [comment]
Hi

`gql_websocket_link ` des support web, can you share code sample or full stack trace; that will help fixing the issue. 


Thanks

**Comment by agent3bood** [comment]
Closing.
