### ISSUE TITLE
[gql_dio_link] Update to dio 4.0.0

### ISSUE THREAD

**Issue by ivatar39** [gql-dart/gql#211]
So I've installed your package, and, unfortunately, it does not support latest dio release.

`Because every version of gql_dio_link depends on dio ^3.0.9 and mocsi_client depends on dio ^4.0.0, gql_dio_link is forbidden.
So, because mocsi_client depends on gql_dio_link ^0.0.4, version solving failed.
pub get failed (1; So, because mocsi_client depends on gql_dio_link ^0.0.4, version solving failed.)`

**Comment by ivatar39** [comment]
I've just realised that it's a duplicate of [https://github.com/gql-dart/gql/issues/206](206). Still waiting for updates, though

**Comment by agent3bood** [comment]
Hi

For now you have to use `Did 3` until this package is migrated to null safety, track our progress here https://github.com/gql-dart/gql/pull/194


I will keep this issue open until the null-safety version is ready.

**Comment by micimize** [comment]
Does https://pub.dev/packages/gql_dio_link/versions/0.1.0-nullsafety.1 use v4?

**Comment by kateile** [comment]
@micimize  it uses 4.0.0-prev3 I guess but not stable 4.0.0

**Comment by agent3bood** [comment]
Closing, latest link version has been upgraded to dio 4.0.0
