### ISSUE TITLE
the idea of [gql_dio_websocket_link]

### ISSUE THREAD

**Issue by teknolojia** [gql-dart/gql#215]
gql_dio_link is amazing and it helps us dealing with server with cookie/session based auth. And with all powerful plugins that dio has already has I think we should have websocket which relies on dio too! So that plugins like [cookie_manager](https://github.com/flutterchina/dio/tree/master/plugins/cookie_manager) can work with websockets too

**Comment by kateile** [comment]
I guess I was drunk

**Comment by agent3bood** [comment]
Reason for closing: `Dio` does not support web socket.
