### ISSUE TITLE
[gql_websocket_link] Passing headers in WebSocketLink

### ISSUE THREAD

**Issue by teknolojia** [gql-dart/gql#219]
My backend uses session based authentication. So I use dio4 along side cookie manager to send/store cookies. It will be really helpful if websocket supports passing cookie headers on every request as well as attempt to reconnect

```dart
  final _wsLink = WebSocketLink(
    'ws://$url',
    config: SocketClientConfig(
      inactivityTimeout: Duration(seconds: 30),
      delayBetweenReconnectionAttempts: Duration(hours: 1),
      autoReconnect: !url.contains('9002'),
      initialPayload: () async {
        //IT WILL BE USEFUL IF SOMETHING LIKE THIS IS CALLED ON EVERY REQUEST
        final cookies = await cookieJar.loadForRequest(Uri.parse(graphqlEndpoint));

        final cookie = cookies
            .where((c) => c.value.length >= 20)
            .map((e) => '${e.name}=${e.value}')
            .toList()
            .join('; ');

        //BELOW DOESN'T WORK
       return {'Cookie': cookie};
      }(),
    ),
  );
```

**Comment by agent3bood** [comment]
Hi

First of all, `initialPayload` is used to send a payload when opening the WebSocket.
To send headers with requests you need to use `gql_transform_link `, something like this [example](https://github.com/gql-dart/gql/blob/master/examples/gql_example_http_auth_link/lib/http_auth_link.dart).

If this does not help, please explain more about the issue, and why is it related to `autoReconnect`.

**Comment by teknolojia** [comment]
I am just a beginner and don't know many things yet. I am currently using this solution [here](https://gist.github.com/micimize/04ee011b445d38ce34193a5225992504) which passes headers to WebSocketLink really well. But  now I want to use Dio4 and after updating packages I just realized web socket backend uses different package  that solution does not work anymore with nullsafety packages.

**Comment by agent3bood** [comment]
Hi again 

`Dio` support `http` protocol only.
`gql_websocket_link` support `ws` protocol, and there is a null-safety pre-release version available.
`gal_transform_link` can be used with any link in the `gql` family.


Also what back-end are you using?

Some examples:

1. Auth in `initialHeaders`
 most of the time authentication is done via `initialHeaders`.

```
 final wsLink = WebSocketLink(
        'wss://example.com/graphql',
        initialHeaders: () => {
          ...authHeaders,
        },
        initialPayload: () => {
          ...clientName,
        },
        autoReconnect: true,
      );
```


2. auth is passed with every operation
Auth example can be used with `gql_websocket_link` also
https://github.com/gql-dart/gql/blob/master/examples/gql_example_http_auth_link/lib/http_auth_link.dart

**Comment by teknolojia** [comment]
I am using Nodejs with `apollo-server-express` .
Please excuse my dumbness but I can't find the field you mentioned above in `gql_websocket_link: ^0.3.0-nullsafety.1`
```
initialHeaders: () => {
          ...authHeaders,
        },
```
of course in `initialHeaders `is exactly what I need to send my cookie headers.

I am just trying to turn the example you provide above to work with web_socket_link but it does nothing for now
```dart
import 'dart:async';

import "package:gql_exec/gql_exec.dart";
import "package:gql_http_link/gql_http_link.dart";
import "package:gql_link/gql_link.dart";
import "package:gql_transform_link/gql_transform_link.dart";
import 'package:gql_websocket_link/gql_websocket_link.dart';
import 'package:meta/meta.dart';

typedef InitialHeaders = FutureOr<Map<String, String>> Function();

class WSLink extends Link {
  Link _link;

  ///Function which will be called when connecting and when retrying to connect
  ///This is async because I need to fetch headers from CookieJar and pass them
  ///here.
  final InitialHeaders initialHeaders;
  final String url;

  WSLink(this.url, {@required this.initialHeaders}) {
    _link = Link.concat(
      WebSocketLink(
        url,
        autoReconnect: true,
        inactivityTimeout: Duration(seconds: 10),
        reconnectInterval: Duration(seconds: 1),
      ),
      TransformLink(requestTransformer: transformRequest),
    );
  }

  Request transformRequest(Request request) {
    ///I NEED TO USE SOMETHING LIKE THIS FOR RETRIEVING COOKIES AND
    ///PASSING THEM IN THE HEADERS
    // final cookies = await cookieJar.loadForRequest(Uri.parse(graphqlEndpoint));

    // final cookie = cookies
    //     .where((c) => c.value.length >= 20)
    //     .map((e) => '${e.name}=${e.value}')
    //     .toList()
    //     .join('; ');

    return request.updateContextEntry<HttpLinkHeaders>(
      (headers) {
        return HttpLinkHeaders(
          headers: <String, String>{
            ...headers?.headers ?? <String, String>{},
            "Cookie": 'cookie',
          },
        );
      },
    );
  }

  @override
  Stream<Response> request(Request request, [forward]) async* {
    yield* _link.request(request, forward);
  }
}
```

**Comment by agent3bood** [comment]
The `authHeaders` is just an object
```
initialHeaders: () => {
          // ...authHeaders,
         'Autherization': 'Bearer myTokenIsHere'
        },
```

**Comment by teknolojia** [comment]
I have updated details in my last comment. Are you on fiverr/wework or something. I just want to release MVP and this is only thing left and no matter how hard I try to thing I can't make it work with just the hints above

**Comment by agent3bood** [comment]
Look me up on the Discord server https://discord.com/invite/G3JGkBY same username

**Comment by agent3bood** [comment]
Closing as no more information has been provided.

**Comment by rajc4c** [comment]
You can pass Headers using `channelGenerator` and setting url to null

`import 'package:web_socket_channel/io.dart';
final _socketLink = WebSocketLink(
      null,
      channelGenerator: () => IOWebSocketChannel.connect(
        gqlLinkWs,
        headers: appdata.token != null
            ? {'Authorization': 'Bearer  ${appdata.token}'}
            : {},
      ),
    );
`

**Comment by rajc4c** [comment]
You can pass Headers using channelGenerator and setting url to null

```
import 'package:web_socket_channel/io.dart';

final _socketLink = WebSocketLink(
      null,
      channelGenerator: () => IOWebSocketChannel.connect(
        gqlLinkWs,
        headers: appdata.token != null
            ? {'Authorization': 'Bearer  ${appdata.token}'}
            : {},
      ),
    );

 ```

**Comment by zombie6888** [comment]
this works with hasura on both web and mobile platforms
```dart
 final wsLink = WebSocketLink(null,
      initialPayload: {"headers": headers},
      channelGenerator: () => WebSocketChannel.connect(
          Uri.parse(params.uri.replaceFirst('https://', 'wss://')),
          protocols: ['graphql-ws']));
```
