### ISSUE TITLE
How to resolve a request on a 304 error?

### ISSUE THREAD

**Issue by NamanShergill** [gql-dart/gql#231]
Getting a 304 error means that cached data is to be given. How can we add an exception for specific error codes?

**Comment by NamanShergill** [comment]
https://github.com/NamanShergill/gql/commit/8009ed343e6411e15443ec242f84e15be3ec07fb

The package should have something like this to give a bit more control over the request.

**Comment by agent3bood** [comment]
@NamanShergill Will this PR https://github.com/gql-dart/gql/pull/210 solve your issue?

**Comment by NamanShergill** [comment]
> @NamanShergill Will this PR #210 solve your issue?

Seems like it would! Although there might be an issue of it being hard to define ranges in this method.

**Comment by agent3bood** [comment]
Before going ahead and approve this issue, let me understand the issue in a better way.

By default (and by convention) GraphQL uses `POST` method for all its operation (query, mutation, subscription).
The `POST` http method is un[safe](https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP), meaning returning *304* for a `POST` operation is considered as error. What server configuration is returning *304* for a `POST` request?

Also can you show me a case of how this issue is handled in other clients (ie Apollo)? I was not able to find issues related to this.

**Comment by NamanShergill** [comment]
> Before going ahead and approve this issue, let me understand the issue in a better way.
> 
> By default (and by convention) GraphQL uses `POST` method for all its operation (query, mutation, subscription).
> The `POST` http method is un[safe](https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP), meaning returning _304_ for a `POST` operation is considered as error. What server configuration is returning _304_ for a `POST` request?
> 
> Also can you show me a case of how this issue is handled in other clients (ie Apollo)? I was not able to find issues related to this.

It's not directly sent by the API itself, but if you're using a package like, say, https://github.com/llfbandit/dio_cache_interceptor and are caching the request through it yourself, that package resolves the request with a 304 status code.

**Comment by agent3bood** [comment]
In the specific case of [dio_cache_interceptor](https://github.com/llfbandit/dio_cache_interceptor), 
you can modify the status code using [onResponse.html](https://pub.dev/documentation/dio_cache_interceptor/latest/dio_cache_interceptor/DioCacheInterceptor/onResponse.html).

I will share this issue on [Discord](https://discord.gg/tFQV72t4) to get more feedback.

**Comment by NamanShergill** [comment]
> In the specific case of [dio_cache_interceptor](https://github.com/llfbandit/dio_cache_interceptor),
> you can modify the status code using [onResponse.html](https://pub.dev/documentation/dio_cache_interceptor/latest/dio_cache_interceptor/DioCacheInterceptor/onResponse.html).
> 
> I will share this issue on [Discord](https://discord.gg/tFQV72t4) to get more feedback.

Unfortunately that part is not exposed by the package to be modifiable without forking the package itself and changing it.

**Comment by agent3bood** [comment]
Check out this example. 

```
  final client = dio.Dio()
    ..interceptors.add(DioCacheInterceptor(options: options))
    ..interceptors.add(dio.InterceptorsWrapper(
        onRequest:(options, handler){
          return handler.next(options); 
        },
        onResponse:(response,handler) {
          response.statusCode = 200; // << change statusCode
          return handler.next(response);
        },
        onError: (dio.DioError e, handler) {
          return  handler.next(e);
        }
    ));
```

**Comment by NamanShergill** [comment]
> Check out this example.
> 
> ```
>   final client = dio.Dio()
>     ..interceptors.add(DioCacheInterceptor(options: options))
>     ..interceptors.add(dio.InterceptorsWrapper(
>         onRequest:(options, handler){
>           return handler.next(options); 
>         },
>         onResponse:(response,handler) {
>           response.statusCode = 200; // << change statusCode
>           return handler.next(response);
>         },
>         onError: (dio.DioError e, handler) {
>           return  handler.next(e);
>         }
>     ));
> ```

Yep this is how I'm planning to do it right now, but it would still be nice to be able to have more flexibility in the package itself regarding this, this kind of feels like a hacky fix.

**Comment by agent3bood** [comment]
Interceptors are made to modify requests or responses.
Also GraphQL does not care about HTTP status codes, so adding this feature will make our package do user land logic.

It might be better to discuss this issue with the * DioCacheInterceptor* maintainer and add a way to modify the status code because it is being set to *304* in [here](https://github.com/llfbandit/dio_cache_interceptor/blob/master/lib/src/model/cache_response.dart#L73).

**Comment by NamanShergill** [comment]
> Interceptors are made to modify requests or responses.
> Also GraphQL does not care about HTTP status codes, so adding this feature will make our package do user land logic.
> 
> It might be better to discuss this issue with the * DioCacheInterceptor* maintainer and add a way to modify the status code because it is being set to _304_ in [here](https://github.com/llfbandit/dio_cache_interceptor/blob/master/lib/src/model/cache_response.dart#L73).

Hmm, you're right, seems like my request is outside the scope of this package. Thank you!
