### ISSUE TITLE
GraphQLError does not have "raw" attribute anymore

### ISSUE THREAD

**Issue by caiotl** [gql-dart/gql#232]
I'm migrating graphql_flutter from 3.1.0 to 5.0.0-nullsafety.2 and I have a problem.
GraphQLError, from gql_exec package does not have a raw attribute anymore. I used to get the "errorType" and "code" from the raw attribute to throw custom exceptions based on this code and type, but now I can't get the raw error anymore.
I'm new to GraphQL and I saw recently an example where this information was in extensions, but I don't know if this is correct. It could be a solution, but I think the backend team would have to refactor a considerable number of code lines. If I could solve it myself, it would be better.
What can I do?

Here is my code, where I used to get this info from "raw":
```dart
extension QueryResultExtension on QueryResult {
  void parseException() {
    if (exception.clientException is NetworkException) {
      throw NoConnectionException();
    } else if (exception.graphqlErrors != null) {
      if (exception.graphqlErrors.first.raw['errorType'] ==
          'UnauthorizedException') {
        throw AuthenticationRequiredException();
      }
      throw GraphQLAPIException.fromJson(
          exception.graphqlErrors.first.raw['errorInfo']);
    }
    throw exception;
  }
}```

**Comment by agent3bood** [comment]
This issue is not related to `gql`, please open it in [graphql-flutter](https://github.com/zino-app/graphql-flutter).
