### ISSUE TITLE
gql_code_gen not null-safety

### ISSUE THREAD

**Issue by Fintasys** [gql-dart/gql#234]
Hey! 
I was using `gql_code_gen: ^0.1.5` so far but with null-safety it doesn't work anymore. As well as the current alpha is not supporting null-safety and has conflict with current hive version.
Also I couldn't find this package here anymore so I was also wondering if it was renamed? 

Thank you

**Comment by smkhalsa** [comment]
> I couldn't find this package here anymore so I was also wondering if it was renamed?

Yes, `gql_code_gen` was replaced by `gql_build`.
