### ISSUE TITLE
Generate dart classes based on schema definitions

### ISSUE THREAD

**Issue by 1awaleed** [gql-dart/gql#244]
I am wondering if `gql` is capable in any way of generating types based on schema definitions? I cannot seem to find any documentation or related questions on this.

for example:

Given the following piece of scheme:
```dart
type Person {
    age: Int
    name: String!
}
```
Can it be converted to sound null safe dart class like this:
```dart
class Person{
  int? age;
  String name;

  Person({this.age, required this.name});

  Person.fromJson(Map<String, dynamic> json){
    age = json['age'];
    name = json['name'];
  }

  Map toJson(){
    Map _data = {};
    _data['age'] = age;
    _data['name'] = name;
    return _data;
  }
}
```

**Comment by agent3bood** [comment]
This features is not added in this package. You have to write your own *code generator* for it.
