### ISSUE TITLE
#imports support ast_builder

### ISSUE THREAD

**Issue by micimize** [gql-dart/gql#27]
Related to https://github.com/comigor/artemis/issues/49 -

I'd like to add `ast_builder` support to `graphql-to-dart`, and having it handle imports internally would simplify it considerably. Examples of this pattern in the js world: [`graphql-import`](https://github.com/Urigo/graphql-import), [`graphql-import-loader`](https://github.com/prisma-labs/graphql-import-loader)

**Comment by klavs** [comment]
@micimize are you interested in importing fragments? Or is it about the type system as well?

**Comment by micimize** [comment]
it's for importing fragments - I ended up implementing this today, so will have a pr showing what I mean in a bit or later today
