### ISSUE TITLE
Make DocumentNode JsonSerializable

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/gql#29]
@klavs, I'm working on a GraphQL client that persists mutations when offline and runs them when the client comes back online.

Can we make the DocumentNode class JsonSerializable?

https://github.com/comigor/artemis/issues/62

**Comment by klavs** [comment]
@smkhalsa, I think serializing to GraphQL string is more memory–efficient and more future–proof as you would not rely on the current version of the AST.

**Comment by smkhalsa** [comment]
Thanks, @klavs. We will just use `printNode' and 'parseString'.
