### ISSUE TITLE
On windows, build_runner fails

### ISSUE THREAD

**Issue by Adherentman** [gql-dart/gql#306]
## info
The build output in the mac environment is
```dart
import 'package:gql/ast.dart' as _i1;

......

const document = _i1.DocumentNode(
    definitions: [libraryInfoList, libraryMenu, shoppingList, libraryRadicals]);

```

but in windows env is

```dart
import 'package:gql/ast.dart' as _i1;
import 'package:ym_academy%5Clibrary%5Cbloc%5C__generated__%5Clibrary.ast.gql.dart'
    as _i2;

.......

const document = _i1.DocumentNode(definitions: [
  _i2.libraryInfoList,
  _i2.libraryMenu,
  _i2.shoppingList,
  _i2.libraryRadicals
]);
```

I don't know why `i2` appears in the window environment。
and also translates `/` to `%5C`

## flutter version
flutter: 2.10.3
## pub version
  gql_build: 0.3.0-alpha+1635149947858
  build_runner: ^2.1.8

**Comment by GabbyOwusu** [comment]
I'm having the same issue, Did you find a fix for this? @Adherentman

**Comment by Adherentman** [comment]
> I'm having the same issue, Did you find a fix for this? @Adherentman

There is no other way, but to temporarily write a shell change file path

**Comment by philipsoeberg** [comment]
In gql_build-0.4.1/lib/src/config.dart I have changed outputPath to:

```
String outputPath(String inputPath) {
  final pathSegments = inputPath.split('/');
  pathSegments.insert(pathSegments.length - 1, outputDir);
  return pathSegments.join('/');
}
```

I can't figure why library:path/path.dart was chosen to split pathSegments rather than just splitting by / since dart import use forward slash https://dart.dev/samples#imports.

At any rate, it solves my problem. I cannot build on windows unless I apply above "fix".
