### ISSUE TITLE
Expression - A non-null value must be returned

### ISSUE THREAD

**Issue by ecoant** [gql-dart/gql#308]
Hello, recently when running `dart run build_runner build` in order to get graphql  query and mutation methods generated by Artemis, I am receiving this error on my build server (Codemagic) but not on my local machine. I have verified the package versions used are the same. Is it possible this package content changed without a bump in version number?

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 803ms

[INFO] Precompiling build script......
[WARNING] ../../../.pub-cache/hosted/pub.dartlang.org/gql_code_builder-0.3.0-alpha+1635885531709/lib/src/ast.dart:618:12: Error: A non-null value must be returned since the return type 'Expression' doesn't allow null.
 - 'Expression' is from 'package:code_builder/src/specs/expression.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/code_builder-4.1.0/lib/src/specs/expression.dart').
Expression _directiveLocation(DirectiveLocation location) {
           ^
[INFO] Precompiling build script... completed, took 11.6s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

**Comment by agent3bood** [comment]
Can you try the latest versions? `gql_code_builder: ^0.5.1`? Also please post the version you are using in your app if possible.

**Comment by HansCraftsman** [comment]
Got the same error too.
I use the following packages for GQL:
```
gql: ^0.13.1
graphql: ^5.0.1
artemis: ^7.2.3-beta
```

**Comment by ecoant** [comment]
> Can you try the latest versions? `gql_code_builder: ^0.5.1`? Also please post the version you are using in your app if possible.

I am using another package: Artemis `7.4.0-beta` - which has a dependecy on `gql_code_builder-0.3.0-alpha+1635885531709`

**Comment by agent3bood** [comment]
As i know codemagic is setup to use the latest Flutter version, so you can check if that is causing the issue.

**Comment by HansCraftsman** [comment]
I've been trying to solve this problem for about 2 hours now.
I'm trying to start a project with different versions of Artemis and Flutter SDK. But I get the same error again and again.
It is interesting that there is another project in which everything works, but in which package I can’t understand the problem - with the same dependencies, the new project cannot generate GQL files
Tried Flutter SDK 2.5.2, 2.5.3, 2.10.4
Artemis - 7.1.0-beta.0 and above

The most interesting thing is that the old project works with Artemis - 7.1.0-beta.0 without errors

**Comment by ecoant** [comment]
> As i know codemagic is setup to use the latest Flutter version, so you can check if that is causing the issue.

It's actually just a pure dart project for me, and I've verified that both Dart versions are the latest (2.16.2) between local and server. I am seeing a similar issue to @HansCraftsman where it suggests an older copy of the same dependency works, but the latest copy of the dependency (gql-code-builder) fails.

**Comment by agent3bood** [comment]
It is possible that when doing `pub get` it get the latest version. Can you try to fix the version in pubspec like this 

`package: 1.0.0` without the `^`.

Otherwise Artemis has to support latest versions.

**Comment by ecoant** [comment]
Confirmed that both the working local version of my project's `pub get` and the codemagic `pub get` both pull down the same version: 
`Downloading gql_code_builder 0.3.0-alpha+1635885531709...`

**Comment by agent3bood** [comment]
https://github.com/gql-dart/gql/blob/master/codegen/gql_code_builder/lib/src/ast.dart#L609

This part of the code does not have any recent changes, we need more info to debug the issue.

**Comment by patrick-enzo** [comment]
I'm running into this problem as well after doing an upgrade command. I also tested this using Flutter version 2.10.4 (latest).

The gql packages used in the project:
```
  gql_dio_link: ^0.1.0
  gql_exec: ^0.3.0
```

I managed to stop this from happening by changing the `gql` version in the pubspec.lock file to go from version` 0.13.1 `to version` 0.13.0.`

**Comment by ecoant** [comment]
Artemis devs have updated the package dependencies and will release the fixed version in 7.7.0, thank you all for your help in tracing this! Another poster on the Artemis issue also provided this interim solution using `dependency_overrides` until the new Artemis version is fixed.

https://github.com/comigor/artemis/issues/386#issuecomment-1098329825

**Comment by knaeckeKami** [comment]
The issue here is incompatible versions of packages gql and gql_code_builder.
package gql own the enum DirectiveLocation. in version 0.13.2, gql added a field `variableDefinition` to that enum. (commit: https://github.com/gql-dart/gql/commit/07bb75c446db7e69e4861aeba14464ce564cea55#diff-712c672327a75d657029771711c068f0b92c5aa859c0d9b58115912abda1be05 )

gql_code_builder has a switch case statement where every value of that enum is handled (here: https://github.com/gql-dart/gql/blob/master/codegen/gql_code_builder/lib/src/ast.dart#L620 ).
But gql_code_builder 0.2.0 does not handle `variableDefinition`, so this code does not compile as not all values of the enum are handled and a non-nullable method would return null.

So, if your are using `gql_code_builder 0.2.0`, use `gql: 0.13.1-alpha+1649345412280(https://pub.dev/packages/gql/versions/0.13.2-alpha+1649345412280)` or earlier. note that you need to pin the version (no leading `^`)  to prevent pub from using 0.13.2 .

**Comment by Raider-hub** [comment]
hello what version of ferry_flutter works with this?

**Comment by knaeckeKami** [comment]
I don't use ferry_flutter, but 0.5.4 should work I think.

**Comment by Raider-hub** [comment]
i did everything exactly as you have instructed. 

i am how ever gretting this  error
FormatException: Invalid UTF-8 byte (at offset 0)
[SEVERE] ferry_generator:req_builder on lib/api/graphql/schema.graphql:

i am currently on flutter version 3.0.1

ferry has really been giving me problems. 
i would appreciate if you can help me set this up on flutter 3.0.1

**Comment by knaeckeKami** [comment]
looks like your schema.graphql is not encoded in UTF-8/ASCII text.
are you on Linux or Mac OS? then you can check the output of the command `file <projectpath>/lib/api/graphql/schema.graphql` . the output should contain  "ASCII text" or "UTF-8 text". 

this can happen if you opened the file with an editor that has set another text encoding as default.
try regenerating your schema.graphql file or converting it to utf-8.

**Comment by Raider-hub** [comment]
i am on windows. 
thank you so much man, i converted it using notepad++ and it has generated the files as expected.
Thanks alot.
