### ISSUE TITLE
Subcription

### ISSUE THREAD

**Issue by redDwarf03** [gql-dart/gql#310]
hello

I need some helps to implement subscription.
I try to find absinthe lib for flutter multiplatforms but I don't find anything.
Now, I'm trying to implement my need with gql-dart lib to do something like that:

```
void waitConfirmations(
    String address, {
    onResult,
    onError,
    onCancel,
    onStart,
    onAbort,
  }) {
    String host =
        Uri.parse(endpoint!).host + ':' + Uri.parse(endpoint!).port.toString();

    AbsintheSocket _socket =
        AbsintheSocket('ws://' + host + '/socket/websocket');

    final String operation =
        """subscription { transactionConfirmed(address: "$address") { nbConfirmations } }""";

    Observer _observer = Observer(
      onAbort: onAbort,
      onCancel: onCancel,
      onError: onError,
      onResult: onResult,
      onStart: onStart,
    );

    Notifier notifier =
        _socket.send(GqlRequest(operation: operation), 'notifierKey');
    notifier.observe(_observer);
  }
```

Could you confirm this is possible with Link ?

Thank you

**Comment by redDwarf03** [comment]
just for info, here the method in js 
```
waitConfirmations: function (address, endpoint, handler) {
     const host = new URL(endpoint).host
     const absintheSocket = withAbsintheSocket.create(
       new Socket(`ws://${host}/socket`)
     );

     const operation = `
       subscription {
         transactionConfirmed(address: "${address}") {
           nbConfirmations
         }
       }
       `
     const notifier = withAbsintheSocket.send(absintheSocket, { operation })

     return withAbsintheSocket.observe(absintheSocket, notifier, {
       onAbort: console.log("abort"),
       onError: function (err) {
         throw err
       },
       onStart: console.log("open"),
       onResult: function (result) {
         if (result.data.transactionConfirmed) {
           return handler(result.data.transactionConfirmed.nbConfirmations)
         }

         throw result
       }
     })
   }
```

**Comment by agent3bood** [comment]
Not sure if that is possible, have a look at this websocket lib that is used by gql_websocket_link https://github.com/gql-dart/gql/blob/master/links/gql_websocket_link/pubspec.yaml#L14

**Comment by redDwarf03** [comment]
Thank you for help
I saw this but I don’t find how to use this to use subscriptions

**Comment by agent3bood** [comment]
Reading the docs for [absinthe](https://hexdocs.pm/absinthe/overview.html), it is a GraphQL server library and according to the docs it works with Apollo client.
So this lib should work as well, is there any specific error you are facing?

**Comment by redDwarf03** [comment]
I have not specific error… I confess I don’t know how to write the code 😫

**Comment by agent3bood** [comment]
You can use the websocket link with Ferry client, have a look at the docs https://ferrygraphql.com/
Also we have  a Discord channel for support https://discord.gg/G3JGkBY 

If there is a specific thing that is not working you can open an issue for it.
