### ISSUE TITLE
when support analyzer ^4.0.0

### ISSUE THREAD

**Issue by takapiroid88** [gql-dart/gql#316]
to success analyzing dart 2.17 code, i need it.

or teach me other resolver.

**Comment by dokumanx** [comment]
I am also getting so many errors because of the analyzer version. When will it be supported?

**Comment by knaeckeKami** [comment]
soon.
In the meantime, check out  https://github.com/gql-dart/gql/issues/308#issuecomment-1192756840 in order to use gql-dart/ ferry with analyzer 3.x.x
