### ISSUE TITLE
__typename on Subscription's

### ISSUE THREAD

**Issue by mario-jerkovic** [gql-dart/gql#320]
Currently I'm have an issue with `__typename` field added to the root subscription generated by `gql_build`

Subscription example:
```graphql
subscription Example(
    $Ids: [ID!]!
    $names: [String!]!
) {
    exampleLiveData(
        ids: $Ids
        names: $names
    ) {
        alias
        processedAt
        recordedAt
        value
    }
}
```

what is generated and sent to the server:

```graphql
subscription Example(
    $Ids: [ID!]!
    $names: [String!]!
) {
  exampleLiveData(Ids: $Ids, names: $names) {
    alias
    processedAt
    recordedAt
    value
    __typename
  }
  __typename # <---- This shouldn't be here
}
```
Error thrown: `GraphOLError Object: Subscription "Example
must select onlv one top level field.`

GraphQL specification: https://spec.graphql.org/June2018/#example-2353b

**Comment by oexza** [comment]
@mario-jerkovic what was the solution to this?
