### ISSUE TITLE
Release gql_http_link stable version

### ISSUE THREAD

**Issue by ueman** [gql-dart/gql#350]
The latest release of gql_http_link is a couple of months old and not compatible with the current stable versions of gql_link and gql_error_link. It would be nice if a new stable release could be made.

**Comment by knaeckeKami** [comment]
Thank you, I wanted to publish with the latest batch of public releases but forgot to bump the version number.
Will do later today.

**Comment by knaeckeKami** [comment]
releases gql_htpp_link 0.4.4
