### ISSUE TITLE
[graphql_http_link] Exception thrown in HttpLink causes app to freeze.

### ISSUE THREAD

**Issue by phetdekde** [gql-dart/gql#356]
When a server respond with a 300 >= status code.
HttpLinkServerException will be thrown, which causes the app to freeze.
https://github.com/gql-dart/gql/blob/master/links/gql_http_link/lib/src/link.dart#L122

In the example below, I intentionally cause a typo in the query to reproduce this error.
But in real life, even though I type everything right.
Sometimes the problem might come from the backend itself, and I couldn't change that backend on my own.

So, it would be great if we could find a way to handling these errors.

```
import 'dart:io';
import 'package:graphql/client.dart';

const getJobsQuery = r'''
query ExampleQuery {
  getChats {
    i
  }
}
''';

void main() async {
  try {
    final graphQLClient = GraphQLClient(
      cache: GraphQLCache(),
      link: HttpLink('https://api.chat.graphql-flutter.dev/graphql'),
    );
    final result = await graphQLClient.query<dynamic>(
      QueryOptions<dynamic>(document: gql(getJobsQuery)),
    );
    if (result.hasException) {
      throw Exception(result.exception!.graphqlErrors[0].message);
    }
    print(result);
  } catch (e) {
    throw Exception(e);
  }
  exit(0);
}
```

**Comment by knaeckeKami** [comment]
When I run your sample, the query completes and has a field set that describes the error.
The app should not freeze because of that if you handle the response correctly.

What would you expect to happen instead if the server responds with an error?

**Comment by phetdekde** [comment]
You are absolutely right. I have my breakpoint on uncaught exception, which is why I thought it freeze.
Now everything works fine!
<img width="184" alt="image" src="https://user-images.githubusercontent.com/45917103/191214475-4f71888f-6470-4f0f-8f77-5bff74aa908b.png">
