### ISSUE TITLE
Unify code duplication of `gql_http_link` and `gql_dio_link`

### ISSUE THREAD

**Issue by ueman** [gql-dart/gql#361]
Both, `gql_http_link` and `gql_dio_link`, share a fair bit of implementation. It would be nice if it could be somehow shared between those two.

The following code snippets are mostly the same:

https://github.com/gql-dart/gql/blob/c13e2fe2e6ca234ff5bc17263e3536ed2c907474/links/gql_http_link/lib/src/link.dart#L16-L52

https://github.com/gql-dart/gql/blob/c13e2fe2e6ca234ff5bc17263e3536ed2c907474/links/gql_dio_link/lib/src/dio_link.dart#L11-L43

Then there's also https://github.com/gql-dart/gql/issues/360

I'm guessing there's also some more, if one searches for it.

**Comment by knaeckeKami** [comment]
Yes, it might be possible to extract a lot of the login in same gql_http package and let both http_link and dio_link depend on it.
