### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tjarvstrand** [gql-dart/gql#368]
Hey guys! `analyzer` 5.x has been out for a couple of months now and the gql codegen packages are quickly becoming incompatible with the latest versions of many other packages. I see that dependencies have already been updated which is great. Would it be possible to get these changes released soon?

Would really appreciate it! 🙂

**Comment by knaeckeKami** [comment]
Hi!
Yes, support for analyzer 5.0 has recently been merged. The changes are available in the latest alpha releases on pub.dev already. 

I will promote them to stable soon.

**Comment by knaeckeKami** [comment]
gql_code_builder 0.7.0 is released.

**Comment by tjarvstrand** [comment]
Awesome! Thanks!
