### ISSUE TITLE
[gql_code_builder] Update to analyzer 5.7+

### ISSUE THREAD

**Issue by chillbrodev** [gql-dart/gql#391]
Hello, I believe I am posting this in the correct spot, but if I am mistaken, please let me know where to file this issue.

I was wondering if it would be possible to update the analyzer dependency to 5.7.1 or above. Currently have to use dependency overrides to work around this. I get this in my output when running `flutter pub get` without the override. ```because artemis 7.11.0-beta.1 depends on gql_code_builder 0.6.0 which depends on analyzer ^4.2.0```

Thanks

**Comment by knaeckeKami** [comment]
the latest version of gql_code_builder supports analyzer  >=4.6.0 <6.0.0. You need to get artemis to update their dependency or use an override.

**Comment by chillbrodev** [comment]
Sounds good, I'll post this over on Artemis repo. Thanks for the info. I'll close this.
