### ISSUE TITLE
[gql_http_link] Exception throwed locally causing stream not generated

### ISSUE THREAD

**Issue by agufagit** [gql-dart/gql#393]
Here is the problem code in `link.dart`

```dart
@override
  Stream<Response> request(
    Request request, [
    NextLink? forward,
  ]) async* {
    final httpResponse = await _executeRequest(request);

    final response = await _parseHttpResponse(httpResponse);

    if (httpResponse.statusCode >= 300 ||
        (response.data == null && response.errors == null)) {
      throw HttpLinkServerException(
        response: httpResponse,
        parsedResponse: response,
      );
    }

    yield Response(
      data: response.data,
      errors: response.errors,
      response: response.response,
      context: _updateResponseContext(response, httpResponse),
    );
  }
```

see [this post on stackoverflow](https://stackoverflow.com/a/63436091) for more detailed explanation

**Comment by knaeckeKami** [comment]
I don't see an issue here. can you clarify?

**Comment by ebsangam** [comment]
@knaeckeKami Hi, I was looking for similar issues and found this. Let me explain. When we don't have internet connection somewhere `link` throws an `ServerException` or above `HttpLinkServerException` which is inside async generator. And if we throwing anything inside the async generator we can't catch the error with `onError` method in the stream. So the exception bubbles up and we can't catch it. 

If we have an async* (async-generator) then we should always handle exceptions internally and yield the result.

I don't know why `onError` does not work. I found something here: https://stackoverflow.com/a/69989916
