### ISSUE TITLE
[graphql_transport_ws] The new subprotocol doesn't auto-reconnect

### ISSUE THREAD

**Issue by agufagit** [gql-dart/gql#411]
When debugging, when app is hot-reloaded, it throws an error

```
I/flutter ( 6092): ResponseFormatException(originalException: type '(dynamic) => Map<String, dynamic>?' is not a subtype of type '(dynamic) => FutureOr<Map<String, dynamic>>?' of 'function result', originalStackTrace: #0      TransportWsClientOptions.graphQLSocketMessageDecoder (package:gql_websocket_link/src/graphql_transport_ws.dart)
graphql_transport_ws.dart:1
I/flutter ( 6092): #1      _ConnectionState._startConnecting.<anonymous closure>.<anonymous closure>
graphql_transport_ws.dart:778
I/flutter ( 6092): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)

```

I expect it to auto-reconnect.  The old protocol (gql_websocket_link.dart) works fine, but the new subprotocol throws this error.

file: graphql_transport_ws.dart

line: 778

**Comment by juancastillo0** [comment]
Are you providing a custom `graphQLSocketMessageDecoder`?

It seems the Function is not properly casted, maybe a solution could be to put the `?` inside the `FutureOr` in `GraphQLSocketMessageDecoder`

Current:
https://github.com/gql-dart/gql/blob/e021a3774f77701a534c427d702df4b7781c4a66/links/gql_websocket_link/lib/src/link.dart#L16-L17

Proposed Solution:
```dart
typedef GraphQLSocketMessageDecoder = FutureOr<Map<String, dynamic>?> Function( 
     dynamic message); 
```

Could you try providing an anonymous callback to the options configuration? 

```dart
TransportWsClientOptions(
  graphQLSocketMessageDecoder: (dynamic message) =>
      jsonDecode(message as String) as FutureOr<Map<String, dynamic>>?
)
```

Thanks!

**Comment by agufagit** [comment]
I'm not providing a custom graphQLSocketMessageDecoder.

The anonymous callback seems to work initially, it's not throwing error anymore.  Not sure how it works with data though.

I'll close this issue after some integration tests in a few days.

Thank you
