### ISSUE TITLE
[gql_build] Overhaul import logic

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/gql#42]
As discussed [here](https://github.com/gql-dart/gql/pull/32#discussion_r368244565), in order to support building fragment data next to the fragment definitions in source, we need to rethink the import implementation.

In addition, I'd like to suggest that we follow the [graphql-import style](https://oss.prisma.io/content/graphql-import/overview#features) for imports...

> Import specific types: `# import A from 'schema.graphql'`
Import multiple types: `# import A, B, C from 'schema.graphql'`
Import all types: `# import * from 'schema.graphql'`
Import root fields: `# import Query.* from 'schema.graphql'`
Import root fields and all types: `# import Query.*, Mutation.*, * from 'schema.graphql'`
Relative paths: `# import Post from "../database/schema.graphql"`

**Comment by klavs** [comment]
I am all for the graphql-import style. I wonder if we can/should support dart-style `package:...` imports.

I tried to do a naïve implementation, but the problem is not that trivial.

**Comment by klavs** [comment]
Builders now take a tree of `SourceNode`s as an input. It is currently powered by a simple import syntax.

The more involved graphql-import-style syntax is not yet supported and currently is not on my roadmap.

**Comment by smkhalsa** [comment]
I'll close for now.

If we decide to go the [inline query](https://github.com/gql-dart/ferry/issues/1#issuecomment-589247175) route, this won't be relevant anyway.
