### ISSUE TITLE
[gql_websocket_link] uuid package version conflict

### ISSUE THREAD

**Issue by memishood** [gql-dart/gql#439]
Hello, is it possible to update `uuid` package to ^4.0.0 that the latest [graphql](https://github.com/zino-hofmann/graphql-flutter/tree/main/packages/graphql) package uses & release a new version? Currently, we cannot upgrade `graphql` version because of this.

I know that I can use dependency overriding but I have a modular project, so I have to use overriding in too many places :/

**Comment by knaeckeKami** [comment]
Sure! A PR would be appreciated, it's probably a small change, maybe even just a version bump if the breaking change does not affect us.

Otherwise I'll have a look, but it could take one or two weeks
