### ISSUE TITLE
Type exception in gql_websocket_link with decoding incoming messages.

### ISSUE THREAD

**Issue by temcewen** [gql-dart/gql#455]
Screenshot of error message with location it's occurring at:
![Untitled](https://github.com/gql-dart/gql/assets/76079324/9e8625ae-733b-4a59-9187-f5f45a74f8be)

The method signature expects a type of `FutureOr<Map<String, dynamic>>?` but the default function returns Map<String, dynamic>?. I believe the issue is that the FutureOr type is nullable, not its subtype. 

Here is a screenshot of the default function:
<img width="599" alt="Screenshot 2024-04-06 at 12 28 16 PM" src="https://github.com/gql-dart/gql/assets/76079324/81317771-0def-474f-a618-8b4374ea8d42">

I made a fix for it myself passing in a function that works as expected. I'll go ahead and make a pull request for it if that works.

**Comment by catapop84** [comment]
From what I remember this error appears in dev mode in flutter, when hot reload is used.
In production (release mode) this will not happen

**Comment by agufagit** [comment]
there is an option in TransportWsClientOptions to make your own decoder:
```dart
TransportWebSocketLink(
        TransportWsClientOptions(
   ...
graphQLSocketMessageDecoder: (dynamic message) => jsonDecode(message as String) as FutureOr<Map<String, dynamic>>?
    ),
)
```
