### ISSUE TITLE
Bring Links up to par with what package:graphql has

### ISSUE THREAD

**Issue by klavs** [gql-dart/gql#57]
- [x] Example of Auth link functionality
- [x] Error Link
- [x] Websocket Link
- [x] File upload
- [x] http_link should have something like the useGETForQueries option as well
- [ ] persisted queries were recently contributed

**Comment by DoctorJohn** [comment]
I wrote an auth link that works with the gql http link. It's similar to the one in the `graphql_flutter` package has. I may contribute mine, but where to put it? It's just 21 lines...

**Comment by klavs** [comment]
Hey @DoctorJohn, welcome!

A new link should go to a new package at the root of this directory.

To kickstart your PR you can start by adding it to the example directory of `gql_httpl_link` so that we can discuss the design.

**Comment by smkhalsa** [comment]
Here's the basic implementation of `ErrorLink` that I'm using in case it's helpful:

```dart
import 'dart:async';
import 'package:ferry/ferry.dart';
import 'package:gql_link/gql_link.dart';
import 'package:gql_exec/gql_exec.dart';

typedef void OnError({
  LinkException linkException,
  List<GraphQLError> graphQLErrors,
});

class ErrorLink extends Link {
  final OnError onError;

  ErrorLink(this.onError);

  @override
  Stream<Response> request(Request request, [forward]) =>
      forward(request).transform(
        StreamTransformer.fromHandlers(
          handleError: (error, stacktrace, sink) {
            if (error is LinkException) {
              onError(linkException: error);
            }
            sink.addError(error);
          },
          handleData: (data, sink) {
            if (data.errors != null && data.errors.isNotEmpty) {
              onError(graphQLErrors: data.errors);
            }
            sink.add(data);
          },
        ),
      );
}

```

**Comment by micimize** [comment]
- [ ] `http_link` should have something like the [`useGETForQueries`](https://github.com/zino-app/graphql-flutter/blob/43ff4d394881c2f3175d3dd96ef7d372dc17e9a0/packages/graphql/lib/src/link/http/link_http.dart#L52) option as well
- [ ] [persisted queries](https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql/lib/src/link/apq/link_persisted_queries.dart) were recently contributed

**Comment by klavs** [comment]
I think `useGETForQueries` wasn't doing anything. Am I wrong?

**Comment by micimize** [comment]
yeah I mean it tells the link to [use GET for queries](https://github.com/zino-app/graphql-flutter/blob/43ff4d394881c2f3175d3dd96ef7d372dc17e9a0/packages/graphql/lib/src/link/http/link_http.dart#L174)
```dart
if (operation.isQuery && config.http.useGETForQueries) {
  config.options['method'] = 'GET';
}
```

**Comment by ram231** [comment]
Is the File Upload Work in Progress? This was my first time using graphql for vue(web) and flutter(mobile). How is it going to be implemented in a way that can be used via [http](https://pub.dev/packages/http) package?

**Comment by micimize** [comment]
@ram231 it isn't a WIP exactly, but at the least porting [the existing `graphql` implementation](https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql/lib/src/link/http/link_http.dart) will be necessary for `graphql/client.dart` v4, which I'm actively working on.

@klavs do you think it's possible to decouple `HttpLink` and `FileUpload` link, or will we have to just have two different links?

Also, should I go ahead and PR my [`NetworkException` code](https://github.com/zino-app/graphql-flutter/blob/modularization/packages/graphql/lib/src/exceptions/network.dart) into [`gql_http_link`'s exceptions](https://github.com/gql-dart/gql/blob/b85a508e97e5039cfada0cdcdbef8a687635edb9/links/gql_http_link/lib/src/exceptions.dart) / [exception handling](https://github.com/gql-dart/gql/blob/1884596904a411363165bcf3c7cfa9dcc2a61c26/links/gql_http_link/lib/src/link.dart#L157-L162)?

**Comment by ram231** [comment]
I'd like to propose that single file and multipart upload in a separate way that there are no type checking and it should be strongly typed. Thanks for the hard work. I hope it'll get to be flutter favorites.

**Comment by klavs** [comment]
>  How is it going to be implemented in a way that can be used via http package?

Well that is THE question. From GraphQL's perspective a file can be a scalar type. But it should be a well-known scalar type, in the sense that links must know about it to support it. 

> do you think it's possible to decouple `HttpLink` and `FileUpload` link, or will we have to just have two different links?

Probably we'll end up implementing file upload within `HttpLink`.

> Also, should I go ahead and PR my NetworkException code into gql_http_link's exceptions / exception handling?

Your `NetworkException` is a specialized version of the `ServerException`. (My appologies for the bad documentation comment.) In a more abstract sense, there is no network, there's only server you are trying to communicate to. This generalization will make more sense when we have a client-side resolver (client-side server) support.

**Comment by micimize** [comment]
@klavs `ServerException` has a `@required Response parsedResponse`, which doesn't make sense when the error involves a failure on the network itself. `NetworkException` would be part of `gql_http_link` regardless.
Maybe the taxonomy should be
```dart
TerminatingLinkException
 ├── ServerException
 └── NetworkException /// in `gql_http_link`
```

**Comment by micimize** [comment]
@klavs Everything but persisted queries has been merged, and I think it's fine if [APQ lives in graphql flutter](https://github.com/zino-app/graphql-flutter/pull/699) or 3rd party module for now.

So, I'd say once `gql_http_link: 0.3.0` is published (and maybe other recent changes) we can close this?
