### ISSUE TITLE
Error when parsing SDL schema

### ISSUE THREAD

**Issue by comigor** [gql-dart/gql#65]
Hey @klavs! I'm getting an error while using the language SDL parser (`parseString`) on some of my examples. It say it can't find the Entity interface while parsing the [Area object](https://gist.github.com/comigor/cc4664e68499e7f330064a5543736371#file-graphbrainz-schema-graphql-L32) even though [it's declared](https://gist.github.com/comigor/cc4664e68499e7f330064a5543736371#file-graphbrainz-schema-graphql-L1114) on the same schema:
```
Error on line 32, column 28 of lib/graphbrainz.schema.graphql: Unknown definition type 'Entity'
   ╷
32 │ type Area implements Node, Entity {
   │                            ^^^^^^
   ╵
package:gql/src/language/parser.dart 175:5   _Parser._parseDefinition
package:gql/src/language/parser.dart 117:22  _Parser._parseMany
package:gql/src/language/parser.dart 142:22  _Parser._parseDocument
package:gql/src/language/parser.dart 41:27   _Parser.parse
package:gql/src/language/parser.dart 17:17   parse
package:gql/src/language/parser.dart 27:5    parseString
```

The full schema, for referece: [graphbrainz.schema.graphql](https://gist.github.com/comigor/cc4664e68499e7f330064a5543736371).

**Comment by comigor** [comment]
And another problem when parsing the [GitHub schema](https://gist.github.com/comigor/5be2f6172e70aa118d99f86f272022a8):
```
Bad state: No element
```

**Comment by klavs** [comment]
@comigor, it should be `type Area implements Node & Entity`

**Comment by klavs** [comment]
@comigor, I was able to parse the official github schema just fine. Would you be able to narrow your SDL to the part which actually fails?

**Comment by klavs** [comment]
It's line 813.
https://gist.github.com/comigor/5be2f6172e70aa118d99f86f272022a8#file-github-schema-graphql-L810-L814

**Comment by comigor** [comment]
Oh, you're absolutely right about the spec, though some tools that convert Introspection queries to SDL seem to generate the SDL with commas.

Do you know if the spec was different before 2018? If it used a comma before, shouldn't we be retro-compatible and parse it as well?

Reference of code used in the conversion:  https://gist.github.com/stubailo/041999ba5b8b15cede60b93ff9a38f53#file-introspection-result-to-sdl-js

**Comment by comigor** [comment]
The GitHub SDL I'm using was also converted from Introspection query, so I think it may be the same (or a similar) problem.

**Comment by klavs** [comment]
A quick search over older versions of the spec (https://spec.graphql.org/) does not reveal any useful info about commas as separators for interfaces.

Comma is actually an ignored token in GraphQL. https://spec.graphql.org/June2018/#sec-Appendix-Grammar-Summary.Ignored-Tokens

It's weir because snippet you gave uses the reference implementation which uses `&` as a separator. https://github.com/graphql/graphql-js/blob/af480089b5fcaa961adb356ef1dca13cf475e75f/src/utilities/printSchema.js#L192

**Comment by comigor** [comment]
Wow that's weird! Apparently I've used a legacy version of this library (of 2 years ago): https://github.com/graphql/graphql-js/blame/652c0323ea2265fd1d001a9ee36fe9232369b75f/src/utilities/schemaPrinter.js#L179

**Comment by comigor** [comment]
So probably GitHub wasn't working due to another spec difference.

**Comment by klavs** [comment]
Yes, the GitHub example had a multi-line comment badly printed, probably.

**Comment by comigor** [comment]
Actually, I'm still not able to parse the GitHub schema from the official source: https://github.com/octokit/graphql-schema

**Comment by klavs** [comment]
That's interesting. You may notice I added a github example borrowed from package:graphql to this repo. It uses the same schema file you are pointing to (the*.graphql one; not *.json transformed).

I had some issues at the build layer, but the parser itself worked just fine without adjustment.

**Comment by comigor** [comment]
I'm now trying to parse the official SDL schema (without conversion) from octokit repos without success.

**Comment by klavs** [comment]
What version of `package:gql` are you using?
What's the error message and/or stacktrace you get?

**Comment by comigor** [comment]
Artemis is now parsing AST schemas directly.
