### ISSUE TITLE
[gql_build] var_builder regression 

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/gql#67]
I'm running into an issue caused by this change:

https://github.com/gql-dart/gql/commit/2ec34002ed4771c628462f432fb1bb03c66eba17#diff-de53cc87c4e8bb475234fd501187c9e0R76

The generated `.var.gql.dart` file now imports from 'package:[path/to/source/file].schema.gql.dart' (which doesn't exist) rather than from the global `.schema.gql.dart` file.

**Comment by smkhalsa** [comment]
@klavs should we revert back to passing in the schemaUrl in var_builder?

**Comment by klavs** [comment]
I think this can be solved in the `gql_build`, by adjusting the Allocator to receive schema url and handling the `#schema` fragment as a special case here https://github.com/gql-dart/gql/blob/master/gql_build/lib/src/utils/writer.dart#L79

**Comment by klavs** [comment]
Semantically it might not be great, but this URI fragment approach is still experimental, but makes the builder a bit easier to implement.

**Comment by smkhalsa** [comment]
> I think this can be solved in the gql_build, by adjusting the Allocator to receive schema url and handling the #schema fragment as a special case.

Ok, makes sense to me.

**Comment by klavs** [comment]
I'm taking this up
