### ISSUE TITLE
[gql_build] duplicate ast imports

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/gql#73]
I'm running into an issue with the new import functionality. If I have a query that uses multiple fragments which themselves use a common fragment, the `ast_builder` will include multiple instances of the import for that common fragment in its List of definitions.

@klavs I assume we can simply check for uniqueness [here](https://github.com/gql-dart/gql/blob/master/gql_code_builder/lib/ast.dart#L22), but let me know your thoughts.

**Comment by klavs** [comment]
I suspected this may happen. The problem is at the `reader.dart`. It should point to already read source nodes if import points to the same file.
But then, the `getRefs` will also need to be adjusted. So maybe we can only change that function...
