### ISSUE TITLE
Add websocket link

### ISSUE THREAD

**Issue by smkhalsa** [gql-dart/gql#76]
moving this from https://github.com/gql-dart/ferry/issues/7

**Comment by iscriptology** [comment]
Any update regarding this?

**Comment by klavs** [comment]
There is no active work going on related to this. Contributions are very welcome.

The plan is to adopt https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/link/web_socket/link_web_socket.dart

**Comment by smkhalsa** [comment]
If graphql-flutter [switches to gql_link](https://github.com/zino-app/graphql-flutter/issues/608), I imagine many others will be looking for a WebSocket link.

**Comment by klavs** [comment]
Yes, that would indeed be a prerequisite. See also https://github.com/gql-dart/gql/issues/57

**Comment by klavs** [comment]
Thanks to @iscriptology this is now implemented and published as https://pub.dev/packages/gql_websocket_link

Note that it's an alpha release.

**Comment by iscriptology** [comment]
hard to miss `gql_websocket_link: ^0.1.1-alpha+1588798058511`
😆
