### ISSUE TITLE
Blank comment lines break parser

### ISSUE THREAD

**Issue by comigor** [gql-dart/gql#99]
I've found that a "blank comment" (lines with only `#` followed by line terminator) _before_ any important line break gql parser.

For instance, any of the following breaks:
```graphql
#
schema {
#
  query: Query
}

type Query {
  object: Object!
#
}

# The next line will be only `#`
#
type Object {
  id: String
}

```

As per [spec "Comments" section](https://spec.graphql.org/June2018/#sec-Comments), it seems they are valid.

Here's a file reproducing this error: [schema.graphql](https://gist.github.com/comigor/6a710fe39536ad2a8cbfaec892852ef7)

**Comment by comigor** [comment]
I'll try to fix this on the parser!

**Comment by klavs** [comment]
It's most likely an off-by-one error in `lexer.dart` `scanComment()`.
